import { Draft } from "./types";

export const MOCK_DRAFTS: Draft[] = [
  { id: "1",  title: "Why AI Copilots Are Changing Code Review",  time: "Oct 24", platform: "WordPress", status: "Published", preview: "AI-powered code review tools are transforming how engineering teams collaborate.\n\nThe key advantage isn't just speed—it's consistency. While human reviewers may miss patterns across large codebases, AI copilots maintain awareness of the entire project context." },
  { id: "2",  title: "The Rise Of Edge Computing In 2024",        time: "Oct 22", platform: "WordPress", status: "Draft",     preview: "Edge computing is reshaping how data is processed, moving computation closer to where data is generated rather than relying on centralized data centers." },
  { id: "3",  title: "Optimizing React Server Components",         time: "Oct 23", platform: "Medium",    status: "Failed",    preview: "React Server Components offer a new paradigm for building performant applications, but optimization requires understanding the boundary between server and client rendering." },
  { id: "4",  title: "Understanding Vector Databases",            time: "Oct 23", platform: "Dev.to",    status: "Retried",   preview: "Vector databases are becoming essential infrastructure for AI applications, enabling semantic search and similarity matching at scale." },
  { id: "5",  title: "Building Scalable APIs With GraphQL",       time: "Oct 25", platform: "Medium",    status: "Published", preview: "GraphQL provides a flexible and efficient alternative to REST APIs, allowing clients to request exactly the data they need." },
  { id: "6",  title: "Demystifying Quantum Computing",            time: "Oct 21", platform: "WordPress", status: "Draft",     preview: "Quantum computing promises to solve problems that are intractable for classical computers, but understanding the fundamentals is the first step." },
  { id: "7",  title: "An Introduction To Progressive Web Apps",   time: "Oct 20", platform: "Dev.to",    status: "Published", preview: "Progressive Web Apps bridge the gap between web and native applications, offering offline support, push notifications, and app-like experiences." },
  { id: "8",  title: "Exploring The Future Of 5G Technology",     time: "Oct 18", platform: "Medium",    status: "Failed",    preview: "5G technology is set to revolutionize connectivity, enabling new use cases from autonomous vehicles to smart city infrastructure." },
  { id: "9",  title: "How Blockchain Is Reshaping Finance",       time: "Oct 19", platform: "WordPress", status: "Retried",   preview: "Blockchain technology is disrupting traditional financial systems, enabling decentralized finance, faster cross-border payments, and greater transparency." },
  { id: "10", title: "The Future of WebAssembly",                 time: "Oct 17", platform: "Dev.to",    status: "Published", preview: "WebAssembly is enabling high-performance applications on the web, bringing near-native execution speeds to the browser." },
  { id: "11", title: "Understanding TypeScript Generics",         time: "Oct 16", platform: "Medium",    status: "Draft",     preview: "TypeScript generics provide a way to create reusable components that work with a variety of types rather than a single one." },
  { id: "12", title: "Deep Dive Into CSS Container Queries",      time: "Oct 15", platform: "WordPress", status: "Published", preview: "Container queries allow developers to apply styles based on the size of a containing element rather than the viewport." },
  { id: "13", title: "Building Real-Time Apps With WebSockets",   time: "Oct 14", platform: "Dev.to",    status: "Failed",    preview: "WebSockets provide a persistent connection between client and server, enabling real-time bidirectional communication." },
  { id: "14", title: "Mastering Git Branching Strategies",        time: "Oct 13", platform: "Medium",    status: "Retried",   preview: "Effective branching strategies are essential for team collaboration and maintaining a clean commit history." },
  { id: "15", title: "Introduction to Rust for JavaScript Devs", time: "Oct 12", platform: "WordPress", status: "Draft",     preview: "Rust offers memory safety without garbage collection, making it an attractive option for performance-critical applications." },
];